language:
  - c
  - cpp

compiler:
  - gcc
  - g++

script: 
  - gcc -o a ./Picnic/Picnic.c
  - gcc -o b ./BoardCover/BoardCover.c
  - g++ -o c ./BoardCover/BoardCover.cpp
  - g++ -o d ./Practice/Practice.cpp
